### ISSUE TITLE
dynamodb-auto-scaling-dev-scaleUp --- Cannot read property 'logger' of undefined

### ISSUE THREAD

**Issue by Opticsponge** [trek10inc/dynamodb-autoscaling#2]
1. ran deploy
2. created table entries via rest API
3 viewing logs in dynamodb-auto-scaling-dev-scaleUp, we are seeing error in logs

`2017-04-16T15:45:54.211Z xxxx SCALE UP FAILED! TypeError: Cannot read property 'logger' of undefined
at scaleUpTable (/var/task/core/AutoScaleService.js:75:9)
at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
at MappingPromiseArray._promiseFulfilled (/var/task/node_modules/bluebird/js/release/map.js:61:38)
at MappingPromiseArray.PromiseArray._iterate (/var/task/node_modules/bluebird/js/release/promise_array.js:114:31)
at MappingPromiseArray.init (/var/task/node_modules/bluebird/js/release/promise_array.js:78:10)
at MappingPromiseArray._asyncInit (/var/task/node_modules/bluebird/js/release/map.js:30:10)
at Async._drainQueue (/var/task/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/var/task/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:666:20)
at tryOnImmediate (timers.js:639:5)
at processImmediate [as _immediateCallback] (timers.js:611:5)`

**Comment by annawang** [comment]
I encountered the same issue. Any suggestion?

**Comment by shortjared** [comment]
@Opticsponge apologies for the delay here, we're looking into this.

**Comment by shortjared** [comment]
`this` should now be fixed. https://github.com/trek10inc/dynamodb-autoscaling/commit/e5eabd02b8413e0d1f5b13dc126042609f02d572
