### ISSUE TITLE
Tables are not scaling up

### ISSUE THREAD

**Issue by jenshult** [trek10inc/dynamodb-autoscaling#7]
I have tried a wide range of ocnfiguration settings, as well as the bare minimum (just the tableName) and the rest of the config by default, but I always get the same result:

```
SCALE UP TABLE FAILED! TypeError: timeSpanDuration.asSeconds is not a function
at getRequest (/var/task/core/AutoScaleService.js:277:44)
at metrics.forEach.metricName (/var/task/core/AutoScaleService.js:302:19)
at Array.forEach (native)
at resolveTableSchema.then.tableSchema (/var/task/core/AutoScaleService.js:299:23)
at tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/var/task/node_modules/bluebird/js/release/promise.js:606:10)
at Async._drainQueue (/var/task/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/var/task/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/var/task/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:666:20)
at tryOnImmediate (timers.js:639:5)
at processImmediate [as _immediateCallback] (timers.js:611:5)
```

The upDuration object stored in the database looks just fine to me, seems like a standard moment object serialized as a JSON.

Are anyone else having these problems?

**Comment by david-nadaraia** [comment]
Please pull latest commits. Number of issues have been resolved...
